### ISSUE TITLE
reth crash loop 

### ISSUE THREAD

**Issue by Kampe** [ethpandaops/ethereum-helm-charts#288]
Seeing this trying to run reth 0.0.13 once it gets to execution

```
 

2024-02-20T20:09:10.044000Z  INFO reth 0.1.0-alpha.19 (6dc30b4) starting |  
-- | --
  |   | /app/bin/reth/src/builder.rs:460:14 |  
  |   | Location: |  
  |   |   |  
  |   |   |  
  |   | 1: invalid type: map, expected a duration |  
  |   | 1:    \| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |  
  |   | 1: 26 \| [stages.execution.max_duration] |  
  |   | 1:    \| |  
  |   | 1: TOML parse error at line 26, column 1 |  
  |   | 0: Bad TOML data |  
  |   | Caused by: |  
  |   |   |  
  |   | Error: Could not load config file "/data/config.toml"



```

Nothing special about how we're initializing the pod or anything with Helm, just normal install of the chart.

values:
```
        persistence:
          enabled: true
          size: 3Ti
          storageClassName: gp3
        serviceMonitor:
          enabled: true
          namespace: monitoring
          labels:
            instance: primary
          path: /metrics
```
