### ISSUE TITLE
GETH command options as k8s ConfigMap?

### ISSUE THREAD

**Issue by khteh** [ethpandaops/ethereum-helm-charts#350]
https://github.com/ethereum/go-ethereum/issues/31034#event-15995118636

How to configure all the command options as k8s ConfigMap?
```
    spec:
      containers:
        - name: geth
          image: ethereum/client-go:v1.14.12
          imagePullPolicy: Always
          args:
            - --holesky
            - --http
            - --http.addr=0.0.0.0
            - --http.vhosts=geth
            - --ws
            - --ws.addr=0.0.0.0
            - --authrpc.jwtsecret=/tmp/jwtsecret
            - --datadir=/data
```
I would love these to be organized into ConfigMap instead of in the STS manifest file. Actually, if you have a sample .toml file used with `--config` for all the options defined in https://github.com/ethpandaops/ethereum-helm-charts/blob/master/charts/geth/values.yaml that will be helpful.
